name: Deploy to AWS Lambda
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Clean build
        run: rm -f index.js
      - name: Build with esbuild
        run: npx esbuild src/index.js --bundle --platform=node --target=node20 --outfile=index.js
      - name: Zip Lambda code
        run: zip -j function.zip index.js
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to AWS Lambda
        run: aws lambda update-function-code --function-name project-01-hono --zip-file fileb://function.zip